# Generated by Django 4.2.1 on 2023-06-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(choices=[('EMIRATES', 'EMIRATES'), ('SPICEJET', 'SPICEJET'), ('QATAR AIRWAYS', 'QATAR AIRWAYS'), ('TATA AIRLINES', 'TATA AIRLINES')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.CharField(choices=[('CHENNAI', 'CHENNAI'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('HYDERABAD', 'HYDERABAD'), ('COIMBATORE', 'COIMBATORE'), ('BANGALORE', 'BANGALORE')], max_length=200)),
                ('destination', models.CharField(choices=[('CHENNAI', 'CHENNAI'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('HYDERABAD', 'HYDERABAD'), ('COIMBATORE', 'COIMBATORE'), ('BANGALORE', 'BANGALORE')], max_length=200)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftb.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftb.routes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftb.user')),
            ],
        ),
    ]
