# Generated by Django 4.2.1 on 2023-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftb', '0003_booking_remove_routes_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
