# Generated by Django 4.2.1 on 2023-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftb', '0004_booking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
