# Generated by Django 4.2.2 on 2023-06-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftb', '0005_remove_booking_user_booking_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
