# Generated by Django 4.2.2 on 2023-06-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftb', '0008_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
